name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm i
      - run: npx tsc
      - run: npm pack
      - run: npx react-native init example
      - run: cp index.js example/
      - run: npm i ../react-native-amap-geolocation-0.0.0.tgz
        working-directory: example
      - run: sed -i.backup -r 's/(enableSeparateBuildPerCPUArchitecture = )false/\1true/' build.gradle
        working-directory: example/android/app
      - run: ./gradlew assembleRelease
        working-directory: example/android
      - uses: actions/upload-artifact@v3
        with:
          name: example.apk
          path: example/android/app/build/outputs/apk/release/app-arm64-v8a-release.apk
